### PR TITLE
feat(): Update endpoints, add trail order and transaction history

### PR DESCRIPTION
**Pull request by mpont91**
## Summary
Bitmart API made a new release adding a new endpoint for supporting trailing orders.
And removed the trailing parameters in submit order.

I did the changes to support their new release.

## Additional Information
Feel free to modify my code and do it better, as it's my first PR, not sure if I'm missing something.

### CODE REVIEW

**Comment by tiagosiebler** [comment]
This is great! Thank you for the PR. Would you mind also increasing the version number in the package json? It makes it easier for me to release the update to NPM after the PR is merged. Since it's a relatively small improvement (without breaking changes), it's enough to increase the smallest number by 1 (to 2.1.10). Thanks!

**Comment by mpont91** [comment]
Done! Let me know if there is something more to do.

**Comment by mpont91** [comment]
Hi @tiagosiebler wait before merging, I noticed it's missing the `transaction-history` endpoint as well.
I will add this one on the same PR, is it okay?

Thanks.

**Comment by tiagosiebler** [comment]
> Hi @tiagosiebler wait before merging, I noticed it's missing the `transaction-history` endpoint as well. I will add this one on the same PR, is it okay?

Yes that's fine, thank you. Don't worry too much about the endpoint function list. We have a script to generate it, so we'll run it with the next PR to fix all the line numbers. Thanks for updating it though!

**Pull request merged**
